name: Sync Fork

on:
  schedule:
    - cron: "0 2 * * 1-5" # Set your workflow to run every day of the week from Monday to Friday at 2:00 UTC
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          token: ${{ secrets.SYNC_FORK_TOKEN }}
          owner: nguyen8amk1
          base: main
          head: main
